-- Canonical ingredient categories for a recipe, generated by the LLM during health
-- analysis (see functions/analyze-recipe-health). Lets rater-affinity analysis on the
-- client group ingredient variants (e.g. "chicken breast" and "chicken thighs" both
-- normalize to "chicken") instead of relying on exact ingredient-text matches.
ALTER TABLE public.dishes
ADD COLUMN canonical_ingredients jsonb DEFAULT '[]'::jsonb;
