import Foundation

/// Cook mode's per-step timers and ingredients: read from `dishes.instruction_details`.
/// This is generated by the `analyze-recipe-steps` edge function, which runs as a
/// database webhook on insert/update.
extension FoodStore {

    /// The recipe's step details. Nil when the recipe has no steps or the background
    /// analysis hasn't finished yet (cook mode then shows text only).
    func stepDetails(for recipe: Recipe) async -> [RecipeStepDetail]? {
        // We now rely on the database webhook to fill instructionDetails.
        // FoodStore's realtime sync will update the `Recipe` struct when it finishes.
        return recipe.currentStepDetails
    }
}
